name: Demo
'on':
  push:
    branches: main
  schedule:
    - cron: 0 1 * * *
  pull_request:
  workflow_dispatch:
jobs:
  run:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        hugo:
          - 0.55.0
          # - latest <---- Uncomment when https://github.com/manixate/jest-hugo/issues/20 is fixed
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '${{ matrix.hugo }}'
          extended: false
      - name: Run demo
        run: |
          npm install
          cd demo
          npm install
          npm run jest
