name: Demo
"on":
  push:
    branches:
      - "**"
  schedule:
    - cron: 0 1 * * *
  pull_request:
  workflow_dispatch:
jobs:
  run:
    runs-on: "${{ matrix.os }}"
    # continue-on-error: true
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        hugo:
          - 0.62.0
          - latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "${{ matrix.hugo }}"
          extended: false
      - name: Run demo
        run: |
          yarn install
          cd demo
          yarn install
          yarn run jest
