name: Prettier
"on":
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run prettier
        run: |
          yarn install
          yarn prettier --check .
